"""Datos de referencia extraídos del formulario de búsqueda de AHEB-BEHA.

Las 115 localidades (con el hueco en el id 5, tal cual las publica la web) del
``<select name="id_localidad">`` de la búsqueda simple. Ver
``tests/fixtures/listado_localidades.html``.
"""

from __future__ import annotations

LOCALIDADES: list[tuple[int, str]] = [
    (1, "Abadiño"),
    (2, "Abanto y Ciérvana-Abanto Zierbena"),
    (3, "Ajangiz"),
    (4, "Alonsotegi"),
    (6, "Amorebieta-Etxano"),
    (7, "Amoroto"),
    (8, "Arakaldo"),
    (9, "Arantzazu"),
    (10, "Areatza"),
    (11, "Arrankudiaga-Zollo"),
    (12, "Arratzu"),
    (13, "Arrieta (Libano de)"),
    (14, "Arrigorriaga"),
    (15, "Artea"),
    (16, "Artzentales"),
    (17, "Atxondo"),
    (18, "Aulesti"),
    (19, "Bakio"),
    (20, "Balmaseda"),
    (21, "Barakaldo"),
    (22, "Barrika"),
    (23, "Basauri"),
    (24, "Bedia"),
    (25, "Berango"),
    (26, "Bermeo"),
    (27, "Berriatua"),
    (28, "Berriz"),
    (29, "Bilbao"),
    (30, "Busturia"),
    (31, "Derio"),
    (32, "Dima"),
    (33, "Durango"),
    (34, "Ea"),
    (35, "Elantxobe"),
    (36, "Elorrio"),
    (37, "Erandio"),
    (38, "Ereño"),
    (39, "Ermua"),
    (40, "Errigoiti"),
    (41, "Etxebarri"),
    (42, "Etxebarria"),
    (43, "Forua"),
    (44, "Fruiz"),
    (45, "Galdakao"),
    (46, "Galdames"),
    (47, "Gamiz-Fika"),
    (48, "Garai"),
    (49, "Gatika"),
    (50, "Gautegiz Arteaga"),
    (51, "Gernika-Lumo"),
    (52, "Getxo"),
    (53, "Gizaburuaga"),
    (54, "Gordexola"),
    (55, "Gorliz"),
    (56, "Güeñes"),
    (57, "Ibarrangelu"),
    (58, "Igorre"),
    (59, "Ispaster"),
    (60, "Iurreta"),
    (61, "Izurtza"),
    (62, "Karrantza Harana/Valle de Carranza"),
    (63, "Kortezubi"),
    (64, "Lanestosa"),
    (65, "Larrabetzu"),
    (66, "Laukiz"),
    (67, "Leioa"),
    (68, "Lekeitio"),
    (69, "Lemoa"),
    (70, "Lemoiz"),
    (71, "Lezama"),
    (72, "Loiu"),
    (73, "Mallabia"),
    (74, "Markina-Xemein"),
    (75, "Maruri-Jatabe"),
    (76, "Mañaria"),
    (77, "Mendata"),
    (78, "Mendexa"),
    (79, "Meñaka"),
    (80, "Morga"),
    (81, "Mundaka"),
    (82, "Mungia"),
    (83, "Munitibar-Arbatzegi Gerrikaitz"),
    (84, "Murueta"),
    (85, "Muskiz"),
    (86, "Muxika"),
    (87, "Nabarniz"),
    (88, "Ondarroa"),
    (89, "Orozko"),
    (90, "Ortuella"),
    (91, "Otxandio"),
    (92, "Plentzia"),
    (93, "Portugalete"),
    (94, "Santurtzi"),
    (95, "Sestao"),
    (96, "Sondika"),
    (97, "Sopela"),
    (98, "Sopuerta"),
    (99, "Sukarrieta"),
    (100, "Trucios-Turtzioz"),
    (101, "Ubidea"),
    (102, "Ugao-Miraballes"),
    (103, "Urduliz"),
    (104, "Urduña/Orduña"),
    (105, "Valle de Trápaga-Trapagaran"),
    (106, "Valle de Villaverde (Villaverde de Trucíos)"),
    (107, "Zaldibar"),
    (108, "Zalla"),
    (109, "Zamudio"),
    (110, "Zaratamo"),
    (111, "Zeanuri"),
    (112, "Zeberio"),
    (113, "Zierbena"),
    (114, "Ziortza-Bolibar"),
    (115, "Usansolo"),
]
