"""personas sin sexo en unicidad

Revision ID: 275c2fe13c61
Revises: 8f81bec701c2
Create Date: 2026-08-15 00:38:58.369290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275c2fe13c61'
down_revision: Union[str, Sequence[str], None] = '8f81bec701c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_persona_identidad'), 'personas', schema='siga', type_='unique')
    op.create_unique_constraint('uq_persona_identidad', 'personas', ['nombre', 'apellido1', 'apellido2'], schema='siga')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_persona_identidad', 'personas', schema='siga', type_='unique')
    op.create_unique_constraint(op.f('uq_persona_identidad'), 'personas', ['nombre', 'apellido1', 'apellido2', 'sexo'], schema='siga', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
