"""soporte_multi_archivo_ahdv_geah

Revision ID: 62dabef5cc75
Revises: e68c7269c9ab
Create Date: 2026-08-15 02:14:21.496058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

archivo_enum = postgresql.ENUM(
    "AHEB_BEHA", "AHDV_GEAH", name="archivo_enum", schema="siga"
)


# revision identifiers, used by Alembic.
revision: str = '62dabef5cc75'
down_revision: Union[str, Sequence[str], None] = 'e68c7269c9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTA IMPORTANTE: esta migración cambia la clave primaria de bautismos/
    # matrimonios/defunciones y la restricción única de scrape_fichas. Si hay
    # un proceso de scraping en marcha (p.ej. "arbol scrape fichas"), sus
    # INSERT con ON CONFLICT en memoria usan la clave ANTIGUA y fallarán en
    # cuanto se aplique esto. Detener el scraping antes de ejecutar
    # "alembic upgrade head" y volver a lanzarlo después (es reanudable).

    # Nuevo valor del enum de estado de ficha: hueco de numeración detectado
    # al procesar (ver FichaStatus.VACIO). Debe ir antes de cualquier uso.
    op.execute("ALTER TYPE siga.ficha_status_enum ADD VALUE IF NOT EXISTS 'VACIO'")

    # Autogenerate no emite el CREATE TYPE del nuevo enum "archivo_enum";
    # hay que crearlo a mano antes de usarlo en los add_column de abajo.
    archivo_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bautismos', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.add_column('defunciones', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.add_column('fondos', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.create_index(op.f('ix_siga_fondos_archivo'), 'fondos', ['archivo'], unique=False, schema='siga')
    op.add_column('localidades', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.create_index(op.f('ix_siga_localidades_archivo'), 'localidades', ['archivo'], unique=False, schema='siga')
    op.create_unique_constraint('uq_localidad_archivo_nombre', 'localidades', ['archivo', 'nombre'], schema='siga')
    op.add_column('matrimonios', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.add_column('parroquias', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.create_index(op.f('ix_siga_parroquias_archivo'), 'parroquias', ['archivo'], unique=False, schema='siga')
    op.add_column('scrape_fichas', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.alter_column('scrape_fichas', 'id_localidad',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='siga')
    op.drop_constraint(op.f('uq_scrape_ficha'), 'scrape_fichas', schema='siga', type_='unique')
    op.create_unique_constraint('uq_scrape_ficha', 'scrape_fichas', ['archivo', 'id_registro', 'sacramento'], schema='siga')
    op.create_index(op.f('ix_siga_scrape_fichas_archivo'), 'scrape_fichas', ['archivo'], unique=False, schema='siga')
    op.add_column('scrape_jobs', sa.Column('archivo', sa.Enum('AHEB_BEHA', 'AHDV_GEAH', name='archivo_enum', schema='siga'), server_default='AHEB_BEHA', nullable=False), schema='siga')
    op.create_index(op.f('ix_siga_scrape_jobs_archivo'), 'scrape_jobs', ['archivo'], unique=False, schema='siga')
    # ### end Alembic commands ###

    # --- Ajustes manuales (autogenerate no detecta cambios de PK ni enums) ---

    # archivo pasa a formar parte de la clave primaria de los 3 sacramentos:
    # sus IDs los asigna cada portal de forma independiente y colisionan
    # entre archivos (comprobado: id_bautismo=1 existe en AHEB-BEHA y en
    # AHDV-GEAH y son personas distintas).
    for tabla, columna in (
        ("bautismos", "id_bautismo"),
        ("matrimonios", "id_matrimonio"),
        ("defunciones", "id_difunto"),
    ):
        op.drop_constraint(f"{tabla}_pkey", tabla, schema="siga", type_="primary")
        op.create_primary_key(f"{tabla}_pkey", tabla, ["archivo", columna], schema="siga")

    # Localidad no tiene un ID estable en todos los archivos (AHDV-GEAH no
    # expone uno en la ficha): a partir de aquí, los ID nuevos se generan
    # automáticamente desde 100000 para no colisionar con los ID 1-115 ya
    # usados por el seed de AHEB-BEHA.
    op.execute(
        "ALTER TABLE siga.localidades ALTER COLUMN id_localidad "
        "ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100000)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Revertir los ajustes manuales antes de que autogenerate quite la
    # columna "archivo" (la necesitamos para reconstruir las PK antiguas).
    op.execute("ALTER TABLE siga.localidades ALTER COLUMN id_localidad DROP IDENTITY IF EXISTS")

    for tabla, columna in (
        ("bautismos", "id_bautismo"),
        ("matrimonios", "id_matrimonio"),
        ("defunciones", "id_difunto"),
    ):
        op.drop_constraint(f"{tabla}_pkey", tabla, schema="siga", type_="primary")
        op.create_primary_key(f"{tabla}_pkey", tabla, [columna], schema="siga")

    # No existe "ALTER TYPE ... DROP VALUE": si se necesita revertir del
    # todo, hay que recrear el tipo `ficha_status_enum` a mano.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siga_scrape_jobs_archivo'), table_name='scrape_jobs', schema='siga')
    op.drop_column('scrape_jobs', 'archivo', schema='siga')
    op.drop_index(op.f('ix_siga_scrape_fichas_archivo'), table_name='scrape_fichas', schema='siga')
    op.drop_constraint('uq_scrape_ficha', 'scrape_fichas', schema='siga', type_='unique')
    op.create_unique_constraint(op.f('uq_scrape_ficha'), 'scrape_fichas', ['id_registro', 'sacramento'], schema='siga', postgresql_nulls_not_distinct=False)
    op.alter_column('scrape_fichas', 'id_localidad',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='siga')
    op.drop_column('scrape_fichas', 'archivo', schema='siga')
    op.drop_index(op.f('ix_siga_parroquias_archivo'), table_name='parroquias', schema='siga')
    op.drop_column('parroquias', 'archivo', schema='siga')
    op.drop_column('matrimonios', 'archivo', schema='siga')
    op.drop_constraint('uq_localidad_archivo_nombre', 'localidades', schema='siga', type_='unique')
    op.drop_index(op.f('ix_siga_localidades_archivo'), table_name='localidades', schema='siga')
    op.drop_column('localidades', 'archivo', schema='siga')
    op.drop_index(op.f('ix_siga_fondos_archivo'), table_name='fondos', schema='siga')
    op.drop_column('fondos', 'archivo', schema='siga')
    op.drop_column('defunciones', 'archivo', schema='siga')
    op.drop_column('bautismos', 'archivo', schema='siga')
    # ### end Alembic commands ###

    archivo_enum.drop(op.get_bind(), checkfirst=True)
