"""esquema inicial siga

Revision ID: 8f81bec701c2
Revises:
Create Date: 2026-08-15 00:33:15.588259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f81bec701c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fondos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_fondos_codigo'), 'fondos', ['codigo'], unique=True, schema='siga')
    op.create_table('localidades',
    sa.Column('id_localidad', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_localidad'),
    schema='siga'
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido1', sa.String(length=200), nullable=True),
    sa.Column('apellido2', sa.String(length=200), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'apellido1', 'apellido2', 'sexo', name='uq_persona_identidad'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_personas_apellido1'), 'personas', ['apellido1'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_personas_apellido2'), 'personas', ['apellido2'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_personas_nombre'), 'personas', ['nombre'], unique=False, schema='siga')
    op.create_table('scrape_fichas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('sacramento', sa.Enum('BAUTISMO', 'MATRIMONIO', 'DIFUNTO', name='sacramento_enum', schema='siga'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'ERROR', name='ficha_status_enum', schema='siga'), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('next_try_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_registro', 'sacramento', name='uq_scrape_ficha'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_scrape_fichas_id_registro'), 'scrape_fichas', ['id_registro'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_scrape_fichas_status'), 'scrape_fichas', ['status'], unique=False, schema='siga')
    op.create_table('parroquias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=300), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('diocesis', sa.String(length=200), nullable=True),
    sa.Column('territorio_historico', sa.String(length=200), nullable=True),
    sa.Column('localidad_texto', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_localidad'], ['siga.localidades.id_localidad'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'nombre', name='uq_parroquia_codigo_nombre'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_parroquias_codigo'), 'parroquias', ['codigo'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_parroquias_id_localidad'), 'parroquias', ['id_localidad'], unique=False, schema='siga')
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sacramento', sa.Enum('BAUTISMO', 'MATRIMONIO', 'DIFUNTO', name='sacramento_enum', schema='siga'), nullable=False),
    sa.Column('id_localidad', sa.Integer(), nullable=False),
    sa.Column('anio_ini', sa.Integer(), nullable=False),
    sa.Column('anio_fin', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'ERROR', name='job_status_enum', schema='siga'), nullable=False),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('paginas_totales', sa.Integer(), nullable=True),
    sa.Column('ultima_pagina', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_localidad'], ['siga.localidades.id_localidad'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sacramento', 'id_localidad', 'anio_ini', 'anio_fin', name='uq_scrape_job'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_scrape_jobs_anio_ini'), 'scrape_jobs', ['anio_ini'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_scrape_jobs_id_localidad'), 'scrape_jobs', ['id_localidad'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False, schema='siga')
    op.create_table('bautismos',
    sa.Column('id_bautismo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_padre', sa.Integer(), nullable=True),
    sa.Column('id_madre', sa.Integer(), nullable=True),
    sa.Column('id_parroquia', sa.Integer(), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('id_fondo', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('codigo_referencia', sa.String(length=200), nullable=True),
    sa.Column('signatura', sa.String(length=200), nullable=True),
    sa.Column('sig_antigua', sa.String(length=200), nullable=True),
    sa.Column('sig_microfilm', sa.String(length=200), nullable=True),
    sa.Column('sig_digital', sa.String(length=200), nullable=True),
    sa.Column('sig_digital_libro', sa.String(length=200), nullable=True),
    sa.Column('pagina', sa.String(length=100), nullable=True),
    sa.Column('fechas_libro', sa.String(length=200), nullable=True),
    sa.Column('html_sha256', sa.String(length=64), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_fondo'], ['siga.fondos.id'], ),
    sa.ForeignKeyConstraint(['id_localidad'], ['siga.localidades.id_localidad'], ),
    sa.ForeignKeyConstraint(['id_madre'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_padre'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_parroquia'], ['siga.parroquias.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['siga.personas.id'], ),
    sa.PrimaryKeyConstraint('id_bautismo'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_bautismos_fecha'), 'bautismos', ['fecha'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_bautismos_id_fondo'), 'bautismos', ['id_fondo'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_bautismos_id_localidad'), 'bautismos', ['id_localidad'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_bautismos_id_madre'), 'bautismos', ['id_madre'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_bautismos_id_padre'), 'bautismos', ['id_padre'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_bautismos_id_parroquia'), 'bautismos', ['id_parroquia'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_bautismos_id_persona'), 'bautismos', ['id_persona'], unique=False, schema='siga')
    op.create_table('defunciones',
    sa.Column('id_difunto', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_conyuge', sa.Integer(), nullable=True),
    sa.Column('id_padre', sa.Integer(), nullable=True),
    sa.Column('id_madre', sa.Integer(), nullable=True),
    sa.Column('id_parroquia', sa.Integer(), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('id_fondo', sa.Integer(), nullable=True),
    sa.Column('edad', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('codigo_referencia', sa.String(length=200), nullable=True),
    sa.Column('signatura', sa.String(length=200), nullable=True),
    sa.Column('sig_antigua', sa.String(length=200), nullable=True),
    sa.Column('sig_microfilm', sa.String(length=200), nullable=True),
    sa.Column('sig_digital', sa.String(length=200), nullable=True),
    sa.Column('sig_digital_libro', sa.String(length=200), nullable=True),
    sa.Column('pagina', sa.String(length=100), nullable=True),
    sa.Column('fechas_libro', sa.String(length=200), nullable=True),
    sa.Column('html_sha256', sa.String(length=64), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_conyuge'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_fondo'], ['siga.fondos.id'], ),
    sa.ForeignKeyConstraint(['id_localidad'], ['siga.localidades.id_localidad'], ),
    sa.ForeignKeyConstraint(['id_madre'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_padre'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_parroquia'], ['siga.parroquias.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['siga.personas.id'], ),
    sa.PrimaryKeyConstraint('id_difunto'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_defunciones_fecha'), 'defunciones', ['fecha'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_defunciones_id_fondo'), 'defunciones', ['id_fondo'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_defunciones_id_localidad'), 'defunciones', ['id_localidad'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_defunciones_id_parroquia'), 'defunciones', ['id_parroquia'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_defunciones_id_persona'), 'defunciones', ['id_persona'], unique=False, schema='siga')
    op.create_table('matrimonios',
    sa.Column('id_matrimonio', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_esposo', sa.Integer(), nullable=True),
    sa.Column('id_esposa', sa.Integer(), nullable=True),
    sa.Column('id_parroquia', sa.Integer(), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('id_fondo', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('codigo_referencia', sa.String(length=200), nullable=True),
    sa.Column('signatura', sa.String(length=200), nullable=True),
    sa.Column('sig_antigua', sa.String(length=200), nullable=True),
    sa.Column('sig_microfilm', sa.String(length=200), nullable=True),
    sa.Column('sig_digital', sa.String(length=200), nullable=True),
    sa.Column('sig_digital_libro', sa.String(length=200), nullable=True),
    sa.Column('pagina', sa.String(length=100), nullable=True),
    sa.Column('fechas_libro', sa.String(length=200), nullable=True),
    sa.Column('html_sha256', sa.String(length=64), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_esposa'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_esposo'], ['siga.personas.id'], ),
    sa.ForeignKeyConstraint(['id_fondo'], ['siga.fondos.id'], ),
    sa.ForeignKeyConstraint(['id_localidad'], ['siga.localidades.id_localidad'], ),
    sa.ForeignKeyConstraint(['id_parroquia'], ['siga.parroquias.id'], ),
    sa.PrimaryKeyConstraint('id_matrimonio'),
    schema='siga'
    )
    op.create_index(op.f('ix_siga_matrimonios_fecha'), 'matrimonios', ['fecha'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_matrimonios_id_esposa'), 'matrimonios', ['id_esposa'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_matrimonios_id_esposo'), 'matrimonios', ['id_esposo'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_matrimonios_id_fondo'), 'matrimonios', ['id_fondo'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_matrimonios_id_localidad'), 'matrimonios', ['id_localidad'], unique=False, schema='siga')
    op.create_index(op.f('ix_siga_matrimonios_id_parroquia'), 'matrimonios', ['id_parroquia'], unique=False, schema='siga')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siga_matrimonios_id_parroquia'), table_name='matrimonios', schema='siga')
    op.drop_index(op.f('ix_siga_matrimonios_id_localidad'), table_name='matrimonios', schema='siga')
    op.drop_index(op.f('ix_siga_matrimonios_id_fondo'), table_name='matrimonios', schema='siga')
    op.drop_index(op.f('ix_siga_matrimonios_id_esposo'), table_name='matrimonios', schema='siga')
    op.drop_index(op.f('ix_siga_matrimonios_id_esposa'), table_name='matrimonios', schema='siga')
    op.drop_index(op.f('ix_siga_matrimonios_fecha'), table_name='matrimonios', schema='siga')
    op.drop_table('matrimonios', schema='siga')
    op.drop_index(op.f('ix_siga_defunciones_id_persona'), table_name='defunciones', schema='siga')
    op.drop_index(op.f('ix_siga_defunciones_id_parroquia'), table_name='defunciones', schema='siga')
    op.drop_index(op.f('ix_siga_defunciones_id_localidad'), table_name='defunciones', schema='siga')
    op.drop_index(op.f('ix_siga_defunciones_id_fondo'), table_name='defunciones', schema='siga')
    op.drop_index(op.f('ix_siga_defunciones_fecha'), table_name='defunciones', schema='siga')
    op.drop_table('defunciones', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_id_persona'), table_name='bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_id_parroquia'), table_name='bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_id_padre'), table_name='bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_id_madre'), table_name='bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_id_localidad'), table_name='bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_id_fondo'), table_name='bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_bautismos_fecha'), table_name='bautismos', schema='siga')
    op.drop_table('bautismos', schema='siga')
    op.drop_index(op.f('ix_siga_scrape_jobs_status'), table_name='scrape_jobs', schema='siga')
    op.drop_index(op.f('ix_siga_scrape_jobs_id_localidad'), table_name='scrape_jobs', schema='siga')
    op.drop_index(op.f('ix_siga_scrape_jobs_anio_ini'), table_name='scrape_jobs', schema='siga')
    op.drop_table('scrape_jobs', schema='siga')
    op.drop_index(op.f('ix_siga_parroquias_id_localidad'), table_name='parroquias', schema='siga')
    op.drop_index(op.f('ix_siga_parroquias_codigo'), table_name='parroquias', schema='siga')
    op.drop_table('parroquias', schema='siga')
    op.drop_index(op.f('ix_siga_scrape_fichas_status'), table_name='scrape_fichas', schema='siga')
    op.drop_index(op.f('ix_siga_scrape_fichas_id_registro'), table_name='scrape_fichas', schema='siga')
    op.drop_table('scrape_fichas', schema='siga')
    op.drop_index(op.f('ix_siga_personas_nombre'), table_name='personas', schema='siga')
    op.drop_index(op.f('ix_siga_personas_apellido2'), table_name='personas', schema='siga')
    op.drop_index(op.f('ix_siga_personas_apellido1'), table_name='personas', schema='siga')
    op.drop_table('personas', schema='siga')
    op.drop_table('localidades', schema='siga')
    op.drop_index(op.f('ix_siga_fondos_codigo'), table_name='fondos', schema='siga')
    op.drop_table('fondos', schema='siga')
    # ### end Alembic commands ###
