"""id_localidad en scrape_fichas

Revision ID: e68c7269c9ab
Revises: 275c2fe13c61
Create Date: 2026-08-15 00:41:05.951176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68c7269c9ab'
down_revision: Union[str, Sequence[str], None] = '275c2fe13c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_fichas', sa.Column('id_localidad', sa.Integer(), nullable=False), schema='siga')
    op.create_index(op.f('ix_siga_scrape_fichas_id_localidad'), 'scrape_fichas', ['id_localidad'], unique=False, schema='siga')
    op.create_foreign_key(None, 'scrape_fichas', 'localidades', ['id_localidad'], ['id_localidad'], source_schema='siga', referent_schema='siga')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scrape_fichas', schema='siga', type_='foreignkey')
    op.drop_index(op.f('ix_siga_scrape_fichas_id_localidad'), table_name='scrape_fichas', schema='siga')
    op.drop_column('scrape_fichas', 'id_localidad', schema='siga')
    # ### end Alembic commands ###
